#!/usr/bin/env python3
"""The measurement-basis contract of ``run_e2e.normalize_result``.

One invariant sits above every other rule here: a reader who divides the
``final_throughput_tok_s`` we publish by the ``baseline_throughput_tok_s`` we
publish must land on the ``throughput_speedup`` we publish. Every test below
protects one of the ways that used to break — a denominator measured hours
before the numerator, a basis switch that moved one side of the ratio, a cold
round compared against a differently-cold one, an arbitration verdict silently
replaced by the intermediate result it was convened to re-check, or a path
advertised for an artifact that was never produced.

Run: python3 -m pytest GEAK/interface/test_run_e2e_measurement_basis.py -v
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent


def _load():
    spec = importlib.util.spec_from_file_location("run_e2e", _HERE / "run_e2e.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


rx = _load()

PATCH_WITH_HUNK = (
    "Provenance: generated by the e2e workflow\n"
    "--- a/mod.py\n+++ b/mod.py\n@@ -1 +1 @@\n-old\n+new\n"
)
PATCH_WITHOUT_HUNK = "Provenance: generated by the e2e workflow\nNo changes to apply.\n"


def _write(path: Path, payload) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(payload, str):
        path.write_text(payload, encoding="utf-8")
    else:
        path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _eval_dir(
    tmp_path: Path,
    *,
    setup_base: float = 1000.0,
    base_leg: float | None = None,
    final_leg: float | None = None,
    setup_cold: float | None = None,
    base_leg_cold: float | None = None,
    final_cold: float | None = None,
    validation: dict | None = None,
) -> Path:
    eval_dir = tmp_path / "e2e_cycle0"
    setup = {"throughput_tok_s_median": setup_base,
             "output_throughput_tok_s_spread_pct": 0.5}
    if setup_cold is not None:
        setup["cold_output_throughput_tok_s"] = setup_cold
    _write(eval_dir / "baseline" / "bench_summary.json", setup)
    if base_leg is not None:
        leg = {"throughput_tok_s_median": base_leg,
               "output_throughput_tok_s_spread_pct": 0.2}
        if base_leg_cold is not None:
            leg["cold_output_throughput_tok_s"] = base_leg_cold
        _write(eval_dir / "validation" / "base" / "bench_summary.json", leg)
    if final_leg is not None:
        leg = {"throughput_tok_s_median": final_leg,
               "output_throughput_tok_s_spread_pct": 0.3}
        if final_cold is not None:
            leg["cold_output_throughput_tok_s"] = final_cold
        _write(eval_dir / "validation" / "final" / "bench_summary.json", leg)
    if validation is not None:
        _write(eval_dir / "director_e2e_validation.json", validation)
    return eval_dir


def _wf(eval_dir: Path, *, base: float, final: float, speedup: float, **extra) -> dict:
    wf = {
        "eval_dir": str(eval_dir),
        "baseline_throughput_tok_s": base,
        "final_throughput_tok_s": final,
        "throughput_speedup": speedup,
        "output_parity": "pass",
    }
    wf.update(extra)
    return wf


def _accepted_candidate(
    eval_dir: Path,
    name: str = "cand_fast_norm",
    *,
    ref: float = 1000.0,
    cand: float = 1100.0,
    delta: float = 10.0,
) -> Path:
    """An accepted intermediate A/B with a real, loadable overlay on disk."""
    cand_dir = eval_dir / "overlay" / name
    _write(cand_dir / "_overlay_manifest.json", {"modules": ["fast_norm"]})
    _write(cand_dir / "sitecustomize.py", "# overlay entry point\n")
    _write(cand_dir / "integrate_result.json", {
        "gate": "accepted",
        "short_name": name.removeprefix("cand_"),
        "e2e_delta_pct": delta,
        "ref_med": ref,
        "cand_med": cand,
        "e2e_throughput_tok_s": cand,
        "accepted_overlay": str(cand_dir),
        "output_parity": "pass",
    })
    return cand_dir


def _assert_self_consistent(out: dict) -> None:
    base = out["baseline_throughput_tok_s"]
    final = out["final_throughput_tok_s"]
    assert base > 0 and final > 0
    assert abs(final / base - out["throughput_speedup"]) <= rx.SPEEDUP_SELF_CONSISTENCY_TOL


# --------------------------------------------------------------------------- #
# the baseline must come from the same session as the final
# --------------------------------------------------------------------------- #
def test_the_re_measured_base_leg_outranks_the_setup_baseline(tmp_path: Path) -> None:
    """The box drifted 5% between Setup and Validate. Only the leg measured
    next to the final can serve as the denominator."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=950.0, final_leg=1000.0)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1000.0, speedup=1.0))

    assert out["baseline_throughput_tok_s"] == 950.0
    basis = out["baseline_basis"]
    assert basis["baseline_basis_source"] == "validation_base_bench_summary"
    assert basis["setup_baseline_tok_s"] == 1000.0
    assert basis["baseline_drift_pct"] == -5.0
    _assert_self_consistent(out)


def test_the_director_drift_correction_is_used_when_the_leg_summary_is_gone(
    tmp_path: Path,
) -> None:
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0, final_leg=1100.0,
        validation={"validation_status": "validated_win",
                    "drift_corrected_baseline_tok_s": 1050.0},
    )
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["baseline_throughput_tok_s"] == 1050.0
    assert out["baseline_basis"]["baseline_basis_source"] == "director_drift_corrected"


def test_a_run_without_a_validate_phase_keeps_the_setup_baseline(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["baseline_throughput_tok_s"] == 1000.0
    assert out["baseline_basis"]["baseline_basis_source"] == "setup_baseline"
    assert out["baseline_basis"]["baseline_drift_pct"] == 0.0


def test_a_recovered_intermediate_win_is_never_re_based(tmp_path: Path) -> None:
    """Its two legs came from one integrate A/B and are already paired; swapping
    in a base leg from a different comparison would break that pairing."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=950.0)
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=1100.0, speedup=1.1,
        recovered_intermediate=True, recovered_from_disk=True,
    ))

    assert out["baseline_throughput_tok_s"] == 1000.0
    assert out["baseline_basis"]["baseline_basis_source"] == "recovered_intermediate_ab"


def test_a_disk_director_fallback_baseline_is_labelled_not_as_setup(
    tmp_path: Path,
) -> None:
    """A result rebuilt from a disk Director artifact (``recovered_from_disk``)
    with no more direct same-session source used to fall through to the
    ``setup_baseline`` label, hiding that the denominator was reconstructed off a
    crashed session rather than measured at Setup. It must carry its own
    provenance, mirroring ``result_source == "disk_director_validation"``.

    This is NOT an intermediate win or a no-gain synthesis, so the re-base guard
    still runs; with no base leg and no drift correction on disk it falls through
    to the recovered-from-disk arm rather than to Setup."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=1100.0, speedup=1.1,
        recovered_from_disk=True,
    ))

    assert out["baseline_throughput_tok_s"] == 1000.0
    assert (
        out["baseline_basis"]["baseline_basis_source"]
        == "disk_director_validation_baseline"
    )
    # The Setup number is still kept for audit; it is simply not the label.
    assert out["baseline_basis"]["setup_baseline_tok_s"] == 1000.0
    _assert_self_consistent(out)


# --------------------------------------------------------------------------- #
# the published pair has the last word on the published speedup
# --------------------------------------------------------------------------- #
def test_a_speedup_that_contradicts_its_own_pair_is_rebuilt_from_it(
    tmp_path: Path,
) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1000.0)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1000.0, speedup=1.15))

    assert out["throughput_speedup"] == 1.0
    assert out["status"] == "no_gain"
    assert out["alignment_metrics"]["speedup_basis"] == "final_over_baseline"
    assert out["alignment_metrics"]["speedup_as_returned"] == 1.15
    _assert_self_consistent(out)


def test_an_agreeing_speedup_is_left_exactly_as_reported(tmp_path: Path) -> None:
    """Within tolerance we keep the arbiter's own number rather than round-trip
    it through our division, so a validated result stays byte-comparable."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["throughput_speedup"] == 1.1
    assert out["alignment_metrics"]["speedup_basis"] == "workflow_return"
    assert out["alignment_metrics"]["speedup_as_returned"] is None


# --------------------------------------------------------------------------- #
# cold rounds are diagnostics, never the promoted number
# --------------------------------------------------------------------------- #
def test_the_cold_ratio_pairs_legs_from_the_same_session(tmp_path: Path) -> None:
    """The Setup cold round ran on a genuinely cold box and the Validate one did
    not, so pairing across them manufactures a gain that the same-session pair
    does not show."""
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0, setup_cold=700.0,
        base_leg=1000.0, base_leg_cold=900.0,
        final_leg=1010.0, final_cold=910.0,
    )
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1010.0, speedup=1.01))
    am = out["alignment_metrics"]

    assert am["cold_pairing"] == "same_session"
    assert am["cold_geak_speedup"] == rx._safe_ratio(910.0, 900.0)   # not 910/700
    assert am["cold_penalty_pct_baseline"] == -10.0
    assert am["cold_penalty_pct_final"] == round((910.0 - 1010.0) / 1010.0 * 100, 3)
    assert out["final_throughput_basis"] == "hot"


def test_cold_pairing_across_phases_is_labelled_as_such(tmp_path: Path) -> None:
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0, setup_cold=700.0,
        final_leg=1010.0, final_cold=910.0,
    )
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1010.0, speedup=1.01))

    assert out["alignment_metrics"]["cold_pairing"] == "setup_vs_validate"


def test_cold_fields_stay_absent_when_no_cold_round_ran(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1010.0)
    am = rx.normalize_result(
        {}, _wf(eval_dir, base=1000.0, final=1010.0, speedup=1.01)
    )["alignment_metrics"]

    assert am["cold_pairing"] is None
    assert am["cold_geak_speedup"] is None
    assert am["cold_penalty_pct_baseline"] is None


# --------------------------------------------------------------------------- #
# Validate's verdict stands; only a MISSING final is backfilled
# --------------------------------------------------------------------------- #
def test_a_measured_no_win_verdict_survives_a_disagreeing_intermediate(
    tmp_path: Path,
) -> None:
    """Validate re-ran the accepted kernel against a fresh base and measured no
    gain. That is the answer, even though the intermediate A/B claimed +10%."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=995.0)
    _accepted_candidate(eval_dir)
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=995.0, speedup=0.995,
        validation_status="validated_no_win",
        accepted_kernels=[{"short_name": "fast_norm", "e2e_delta_pct": 10.0}],
    ))

    assert out["status"] == "no_gain"
    assert out["result_source"] == "workflow_return"
    assert out["final_throughput_tok_s"] == 995.0
    assert out["validation_evidence"]["intermediate_win_not_confirmed"] is True
    _assert_self_consistent(out)


def test_a_missing_final_is_backfilled_from_the_best_intermediate(
    tmp_path: Path,
) -> None:
    """The Validate bench died, so there is no verdict to respect — the real
    parity-checked win on disk must not be discarded with it."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    cand_dir = _accepted_candidate(eval_dir, ref=1000.0, cand=1100.0, delta=10.0)
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=0.0, speedup=0.0,
        accepted_kernels=[{"short_name": "fast_norm", "e2e_delta_pct": 10.0}],
    ))

    assert out["status"] == "ok"
    assert out["result_source"] == "disk_intermediate_win"
    assert out["final_throughput_tok_s"] == 1100.0
    assert out["baseline_throughput_tok_s"] == 1000.0
    assert out["final_overlay"] == str(cand_dir)
    assert out["validation_evidence"]["validate_final_missing"] is True
    _assert_self_consistent(out)


def test_the_crashed_director_record_is_kept_as_evidence(tmp_path: Path) -> None:
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0,
        validation={"validation_status": "final_bench_failed",
                    "director_verified_throughput_tok_s": 0.0},
    )
    _accepted_candidate(eval_dir)
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=0.0, speedup=0.0,
        accepted_kernels=[{"short_name": "fast_norm", "e2e_delta_pct": 10.0}],
    ))

    assert out["validation_evidence"]["validation_status"] == "final_bench_failed"
    assert out["validation_evidence"]["validate_final_missing"] is True


# --------------------------------------------------------------------------- #
# only real artifacts get a path
# --------------------------------------------------------------------------- #
def test_a_marker_only_overlay_and_a_hunkless_patch_report_nothing(
    tmp_path: Path,
) -> None:
    """Finalize writes both unconditionally: the overlay gets a placeholder file
    and the patch gets a kilobyte of preamble, so existence and size both lie."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1000.0)
    _write(eval_dir / "final" / "overlay" / "EMPTY_NO_ACCEPTED_OVERLAY.txt", "none\n")
    _write(eval_dir / "final" / "final_patch.diff", PATCH_WITHOUT_HUNK)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1000.0, speedup=1.0))

    assert out["final_overlay"] == ""
    assert out["final_patch"] == ""


def test_a_real_overlay_and_a_hunked_patch_report_their_paths(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _write(eval_dir / "final" / "overlay" / "_overlay_manifest.json", {"modules": ["m"]})
    _write(eval_dir / "final" / "overlay" / "sitecustomize.py", "# entry\n")
    _write(eval_dir / "final" / "final_patch.diff", PATCH_WITH_HUNK)
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["final_overlay"] == str(eval_dir / "final" / "overlay")
    assert out["final_patch"] == str(eval_dir / "final" / "final_patch.diff")


def test_an_overlay_without_a_sitecustomize_is_not_advertised(tmp_path: Path) -> None:
    """PYTHONPATH activates an overlay through its root ``sitecustomize.py`` and
    nothing else. A manifest beside no entry point, a loose module, or a
    loadable ``cand_*`` child are all inert at the path we would hand back."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    overlay = eval_dir / "final" / "overlay"
    _write(overlay / "_overlay_manifest.json", {"modules": ["m"]})
    _write(overlay / "fast_norm.py", "# a module nobody imports\n")
    _write(overlay / "cand_fast_norm" / "sitecustomize.py", "# entry, one level down\n")
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["final_overlay"] == ""


def test_a_config_only_overlay_is_not_advertised_as_a_kernel_overlay(
    tmp_path: Path,
) -> None:
    """The config-only overlay imports cleanly and installs nothing. Handing it
    back books a pure config win as a kernel win on the consumer's side."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    overlay = eval_dir / "final" / "overlay"
    _write(overlay / "sitecustomize.py", "# entry\n")
    _write(overlay / "_overlay_manifest.json", {
        "modules": [], "rebinds": [],
        "note": "config-only result: no kernel overlay accepted",
    })
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["final_overlay"] == ""


def test_an_unreadable_manifest_is_not_a_loadable_overlay(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    overlay = eval_dir / "final" / "overlay"
    _write(overlay / "sitecustomize.py", "# entry\n")
    (overlay / "_overlay_manifest.json").write_text("{ truncated", encoding="utf-8")
    out = rx.normalize_result({}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1))

    assert out["final_overlay"] == ""


def test_accepted_config_publishes_a_validated_env_map(tmp_path: Path) -> None:
    """The env string is assembled from launch-script lines, so shell syntax
    rides along with it. Consumers that re-split it have exported ``RUN_EVAL``
    as ``true;`` and ``)`` as a variable name; GEAK does the split once and
    says which fragments it could not account for."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    wf = _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1)
    wf["accepted_config"] = {
        "flags": "--mem-fraction-static 0.95",
        "env": 'SGLANG_USE_AITER=1 RUN_EVAL=true; BACKEND=sglang; GPU=0; EXTRA_ENV=).',
    }
    config = rx.normalize_result({}, wf)["accepted_config"]

    assert config["env_map"] == {
        "SGLANG_USE_AITER": "1", "RUN_EVAL": "true",
        "BACKEND": "sglang", "GPU": "0",
    }
    assert config["env_unparsed"] == ["EXTRA_ENV=)."]
    # The raw string is preserved: it is what the run actually exported.
    assert "EXTRA_ENV=)." in config["env"]


def test_an_overlay_recorded_at_a_stale_path_is_found_under_the_eval_dir(
    tmp_path: Path,
) -> None:
    """Runs get archived and remounted; the product is still there even when the
    path baked into the return no longer resolves."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _write(eval_dir / "final" / "overlay" / "_overlay_manifest.json", {"modules": ["m"]})
    _write(eval_dir / "final" / "overlay" / "sitecustomize.py", "# entry\n")
    out = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=1100.0, speedup=1.1,
        final_overlay="/gone/e2e_cycle0/final/overlay",
    ))

    assert out["final_overlay"] == str(eval_dir / "final" / "overlay")


def test_a_recovered_win_hands_back_the_candidate_overlay_that_produced_it(
    tmp_path: Path,
) -> None:
    """A win recovered before Finalize has no final/ bundle, but the code that
    won is on disk in the candidate's own overlay."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    cand_dir = _accepted_candidate(eval_dir)
    recovered = rx._recover_best_intermediate_win(eval_dir)

    assert recovered is not None
    assert recovered["final_overlay"] == str(cand_dir)


def test_a_config_only_win_reports_no_overlay(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    cand_dir = eval_dir / "overlay" / "cand_env_tuning"
    _write(cand_dir / "integrate_result.json", {
        "gate": "accepted",
        "short_name": "env_tuning",
        "winner_kind": "env",
        "e2e_delta_pct": 4.0,
        "ref_med": 1000.0,
        "cand_med": 1040.0,
        "apply_env": "FOO=1",
    })
    recovered = rx._recover_best_intermediate_win(eval_dir)

    assert recovered is not None
    assert recovered["final_overlay"] == ""
    assert recovered["accepted_config"]["env"] == "FOO=1"


# --------------------------------------------------------------------------- #
# the evidence a reader needs to judge the number
# --------------------------------------------------------------------------- #
def test_a_delta_inside_the_noise_band_is_reported_as_insignificant(
    tmp_path: Path,
) -> None:
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1005.0,
        validation={"validation_status": "validated_no_win", "noise_band_pct": 2.0},
    )
    ev = rx.normalize_result(
        {}, _wf(eval_dir, base=1000.0, final=1005.0, speedup=1.005)
    )["validation_evidence"]

    assert ev["validation_status"] == "validated_no_win"
    assert ev["delta_pct"] == 0.5
    assert ev["noise_band_pct"] == 2.0
    assert ev["significance_threshold_pct"] == 2.0
    assert ev["delta_exceeds_noise"] is False
    # The two criteria answer different questions and are allowed to disagree:
    # these benches repeat tightly enough to separate 0.5%, but the Director
    # declared a 2% band for the box, and the wider of the two governs.
    assert ev["spreads_non_overlapping"] is True


def test_a_delta_clear_of_both_spreads_is_reported_as_significant(
    tmp_path: Path,
) -> None:
    eval_dir = _eval_dir(
        tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0,
        validation={"validation_status": "validated_win", "noise_band_pct": 1.0},
    )
    ev = rx.normalize_result(
        {}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1)
    )["validation_evidence"]

    assert ev["delta_pct"] == 10.0
    assert ev["delta_exceeds_noise"] is True
    assert ev["spreads_non_overlapping"] is True
    assert ev["baseline_spread_pct"] == 0.2
    assert ev["final_spread_pct"] == 0.3


def test_an_unknown_spread_is_never_assumed_tight(tmp_path: Path) -> None:
    """With no final leg to measure scatter on, the intervals cannot be shown to
    be apart — which is different from showing they are."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    ev = rx.normalize_result({}, _wf(
        eval_dir, base=1000.0, final=1100.0, speedup=1.1,
        recovered_intermediate=True, recovered_from_disk=True,
    ))["validation_evidence"]

    assert ev["final_spread_pct"] is None
    assert ev["spreads_non_overlapping"] is None


def test_the_promoted_final_is_compared_with_the_same_config_orchestrator_number(
    tmp_path: Path,
) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    wf = _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1)

    beaten = rx.normalize_result({"orchestrator_best_tput_same_config": 1050.0}, wf)
    assert beaten["validation_evidence"]["beats_orchestrator_same_config"] is True

    not_beaten = rx.normalize_result({"orchestrator_best_tput_same_config": 1200.0}, wf)
    assert not_beaten["validation_evidence"]["beats_orchestrator_same_config"] is False


# --------------------------------------------------------------------------- #
# the same config can still be a different stack
# --------------------------------------------------------------------------- #
ACCELERATED_SERVER_LOG = (
    "(APIServer pid=1) INFO [kernel.py:276] Final IR op priority after setting "
    "platform defaults: IrOpPriorityConfig(rms_norm=['aiter', 'native'])\n"
    "(EngineCore pid=2) INFO [__init__.py:563] Selected AiterFp8BlockScaledMMKernel "
    "for Fp8LinearMethod\n"
    "(EngineCore pid=2) INFO [fp8.py:296] Using AITER Fp8 MoE backend out of "
    "potential backends: ['AITER', 'TRITON']\n"
    "(EngineCore pid=2) [aiter] import module_aiter_core\n"
)
FALLBACK_SERVER_LOG = (
    "(APIServer pid=1) INFO [kernel.py:276] Final IR op priority after setting "
    "platform defaults: IrOpPriorityConfig(rms_norm=['native'])\n"
    "(EngineCore pid=2) INFO [__init__.py:563] Selected TritonFp8BlockScaledMMKernel "
    "for Fp8LinearMethod\n"
    "(EngineCore pid=2) INFO [fp8.py:376] Using TRITON Fp8 MoE backend out of "
    "potential backends: ['AITER', 'TRITON']\n"
)


def _with_launcher(monkeypatch, launcher: str, script: str = "", source: str = ""):
    monkeypatch.setenv("BENCH_LAUNCHER", launcher)
    monkeypatch.setenv("MAGPIE_LAUNCH_SCRIPT", script)
    monkeypatch.setenv("MAGPIE_LAUNCH_SCRIPT_SOURCE", source)


def test_the_kernels_each_leg_actually_selected_are_recorded(
    tmp_path: Path, monkeypatch
) -> None:
    """Two servers can take the same flags and come up on different kernels.
    result.json has to say which ones, or the only record is a server log."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _write(eval_dir / "baseline" / "server.log", FALLBACK_SERVER_LOG)
    _write(eval_dir / "validation" / "base" / "server.log", ACCELERATED_SERVER_LOG)
    _with_launcher(monkeypatch, "native")

    stack = rx.normalize_result(
        {}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1)
    )["serving_stack"]

    assert stack["baseline"]["aiter_mentions"] == 1  # only the potential-backends list
    assert any("Triton" in pick for pick in stack["baseline"]["kernel_picks"])
    assert stack["validation_base"]["aiter_mentions"] == 6
    assert any("Aiter" in pick for pick in stack["validation_base"]["kernel_picks"])
    # The pid / module prefix is stripped so the pick reads as the pick.
    assert stack["baseline"]["kernel_picks"][0].startswith("Final IR op priority")


def test_a_leg_that_left_no_server_log_reports_no_signals(tmp_path: Path) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0)
    stack = rx.normalize_result(
        {}, _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1)
    )["serving_stack"]

    assert stack["baseline"] == {}
    assert stack["validation_base"] == {}


def test_a_divergence_across_two_launch_recipes_is_not_called_a_measurement_gap(
    tmp_path: Path, monkeypatch
) -> None:
    """GEAK's own adapter launched the server, so the orchestrator's reference
    was measured on a different stack. The status has to say that rather than
    imply GEAK measured slow."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _with_launcher(monkeypatch, "native")

    out = rx.normalize_result(
        {"orchestrator_best_tput_same_config": 1130.0},
        _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1),
    )

    assert out["baseline_basis"]["current_best_same_config_divergence_pct"] == -11.5
    assert out["baseline_alignment"]["status"] == "warning_recipe_unaligned"
    assert out["baseline_alignment"]["recipe_aligned_with_orchestrator"] is False
    assert out["serving_stack"]["launcher"] == "native"


def test_the_same_divergence_under_a_shared_recipe_stays_a_plain_warning(
    tmp_path: Path, monkeypatch
) -> None:
    """Same number, but both harnesses launched through the same script — now it
    really is a measurement signal and must not be excused as a recipe gap."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _with_launcher(monkeypatch, "magpie", "/ix/benchmarks/vllm_mi355x.sh", "launch_recipe")

    out = rx.normalize_result(
        {"orchestrator_best_tput_same_config": 1130.0},
        _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1),
    )

    assert out["baseline_alignment"]["status"] == "warning"
    assert out["baseline_alignment"]["recipe_aligned_with_orchestrator"] is True
    stack = out["serving_stack"]
    assert stack["launcher"] == "magpie"
    assert stack["launch_script"] == "/ix/benchmarks/vllm_mi355x.sh"
    assert stack["launch_script_source"] == "launch_recipe"


def test_an_aligned_run_is_never_downgraded_by_the_recipe_check(
    tmp_path: Path, monkeypatch
) -> None:
    """The recipe only reclassifies a divergence that already breached the
    threshold; a run inside the band stays `aligned` either way."""
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _with_launcher(monkeypatch, "native")

    out = rx.normalize_result(
        {"orchestrator_best_tput_same_config": 1000.0},
        _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1),
    )

    assert out["baseline_alignment"]["status"] == "aligned"


def test_the_report_flags_an_unaligned_recipe_for_a_human(tmp_path: Path, monkeypatch) -> None:
    eval_dir = _eval_dir(tmp_path, setup_base=1000.0, base_leg=1000.0, final_leg=1100.0)
    _with_launcher(monkeypatch, "native")
    unaligned = rx.normalize_result(
        {"orchestrator_best_tput_same_config": 1130.0},
        _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1),
    )
    _with_launcher(monkeypatch, "magpie", "/ix/benchmarks/vllm_mi355x.sh")
    aligned = rx.normalize_result(
        {"orchestrator_best_tput_same_config": 1130.0},
        _wf(eval_dir, base=1000.0, final=1100.0, speedup=1.1),
    )

    unaligned_section = rx._render_baseline_alignment_section(unaligned)
    aligned_section = rx._render_baseline_alignment_section(aligned)

    assert "Server launch recipe: `native`" in unaligned_section
    assert "did not serve the same stack" in unaligned_section
    assert "Server launch recipe: `magpie`" in aligned_section
    assert "did not serve the same stack" not in aligned_section
    assert unaligned_section.count(rx.BASELINE_ALIGNMENT_BEGIN) == 1
